#!/bin/bash
# ============================================================
# BODHI — Interactive Setup Wizard
# Run: bash scripts/setup.sh
# ============================================================

set -e

BODHI_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$BODHI_DIR/.env"

# Colors
AMBER='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
DIM='\033[0;90m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${AMBER}${BOLD}  ╔══════════════════════════════════╗${NC}"
echo -e "${AMBER}${BOLD}  ║        BODHI — Setup Wizard      ║${NC}"
echo -e "${AMBER}${BOLD}  ║    See yourself clearly.         ║${NC}"
echo -e "${AMBER}${BOLD}  ╚══════════════════════════════════╝${NC}"
echo ""

# ─── Helper ───
check() { echo -e "  ${GREEN}✓${NC} $1"; }
fail()  { echo -e "  ${RED}✗${NC} $1"; }
hint()  { echo -e "  ${DIM}↳ $1${NC}"; }

prompt_value() {
  local varname="$1" prompt="$2" default="$3"
  if [ -n "$default" ]; then
    read -rp "  $prompt [$default]: " value
    eval "$varname=\"${value:-$default}\""
  else
    while true; do
      read -rp "  $prompt: " value
      if [ -n "$value" ]; then
        eval "$varname=\"$value\""
        break
      fi
      echo -e "  ${RED}This field is required.${NC}"
    done
  fi
}

# ─── Step 1: Prerequisites ───
echo -e "${BOLD}Step 1: Checking prerequisites${NC}"
echo ""

MISSING=0

# Node.js
if command -v node &> /dev/null; then
  NODE_V=$(node -v | sed 's/v//')
  NODE_MAJOR=$(echo "$NODE_V" | cut -d. -f1)
  if [ "$NODE_MAJOR" -ge 22 ]; then
    check "Node.js $NODE_V"
  else
    fail "Node.js $NODE_V (need 22+)"
    hint "brew install node  OR  https://nodejs.org"
    MISSING=1
  fi
else
  fail "Node.js not found"
  hint "brew install node  OR  https://nodejs.org"
  MISSING=1
fi

# npm
if command -v npm &> /dev/null; then
  check "npm $(npm -v)"
else
  fail "npm not found"
  MISSING=1
fi

# Claude Code CLI
if command -v claude &> /dev/null; then
  check "Claude Code CLI installed"
else
  fail "Claude Code CLI not found"
  hint "npm install -g @anthropic-ai/claude-code"
  MISSING=1
fi

if [ $MISSING -eq 1 ]; then
  echo ""
  echo -e "${RED}Please install the missing prerequisites and re-run this script.${NC}"
  exit 1
fi

# Claude Code auth check
echo ""
echo -e "${DIM}  Checking Claude Code authentication...${NC}"
if claude --version &> /dev/null 2>&1; then
  check "Claude Code accessible"
else
  fail "Claude Code not authenticated"
  hint "Run: claude auth login"
  echo ""
  echo -e "${AMBER}You can continue setup and authenticate later.${NC}"
fi

echo ""

# ─── Step 2: Check existing .env ───
if [ -f "$ENV_FILE" ]; then
  echo -e "${AMBER}An .env file already exists.${NC}"
  read -rp "  Overwrite it? (y/N): " OVERWRITE
  if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
    echo "  Keeping existing .env. Skipping to build step."
    SKIP_ENV=1
  fi
fi

if [ "$SKIP_ENV" != "1" ]; then
  # ─── Step 3: Your Name ───
  echo -e "${BOLD}Step 2: About you${NC}"
  echo ""
  prompt_value OWNER_NAME "What's your name? (BODHI will greet you by name)" ""
  echo ""

  # ─── Step 4: Database ───
  echo -e "${BOLD}Step 3: Database (Supabase PostgreSQL)${NC}"
  echo ""
  hint "Create a free project at https://supabase.com/dashboard"
  hint "Go to Settings > Database > Connection string > URI"
  hint "Make sure to enable pgvector extension:"
  hint "  SQL Editor > New Query > CREATE EXTENSION IF NOT EXISTS vector;"
  echo ""
  prompt_value DATABASE_URL "Paste your DATABASE_URL" ""
  echo ""

  # ─── Step 5: Telegram ───
  echo -e "${BOLD}Step 4: Telegram Bot${NC}"
  echo ""
  hint "Open Telegram, message @BotFather, send /newbot"
  hint "Copy the bot token it gives you"
  echo ""
  prompt_value TELEGRAM_TOKEN "Telegram Bot Token" ""
  echo ""
  hint "To get your user ID, message @userinfobot on Telegram"
  echo ""
  prompt_value TELEGRAM_USER_ID "Your Telegram User ID (numbers)" ""
  echo ""

  # ─── Step 6: Voyage AI ───
  echo -e "${BOLD}Step 5: Voyage AI (Memory Embeddings)${NC}"
  echo ""
  hint "Get a free API key at https://dash.voyageai.com"
  echo ""
  prompt_value VOYAGE_KEY "Voyage AI API Key" ""
  echo ""

  # ─── Step 7: Timezone ───
  echo -e "${BOLD}Step 6: Timezone${NC}"
  echo ""
  DETECTED_TZ=$(cat /etc/timezone 2>/dev/null || readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||' || echo "UTC")
  prompt_value TIMEZONE "Your timezone" "$DETECTED_TZ"
  echo ""

  # ─── Step 8: Write .env ───
  echo -e "${BOLD}Writing .env...${NC}"

  cat > "$ENV_FILE" << ENVEOF
# ============================================================
# BODHI — Environment Variables
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M')
# ============================================================

# --- Required ---

BODHI_OWNER_NAME=$OWNER_NAME

TELEGRAM_BOT_TOKEN=$TELEGRAM_TOKEN
TELEGRAM_ALLOWED_USER_ID=$TELEGRAM_USER_ID

DATABASE_URL=$DATABASE_URL

VOYAGE_API_KEY=$VOYAGE_KEY

# --- Server ---

PORT=4000
NODE_ENV=development
BODHI_TIMEZONE=$TIMEZONE

# --- Optional Integrations (uncomment when ready) ---

# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# NOTION_API_KEY=
# GITHUB_TOKEN=
# VERCEL_TOKEN=
# GROQ_API_KEY=
ENVEOF

  check ".env created"
  echo ""
fi

# ─── Step 9: Install Dependencies ───
echo -e "${BOLD}Step 7: Installing dependencies...${NC}"
echo ""
cd "$BODHI_DIR"
npm install
check "Dependencies installed"
echo ""

# ─── Step 10: Build ───
echo -e "${BOLD}Step 8: Building all packages...${NC}"
echo ""
npm run build
check "Build complete"
echo ""

# ─── Step 11: Database Migration ───
echo -e "${BOLD}Step 9: Setting up database tables...${NC}"
echo ""

# Source .env for drizzle-kit
set -a
source "$ENV_FILE"
set +a

cd "$BODHI_DIR/packages/db"
npx drizzle-kit push --force 2>&1 || {
  fail "Database migration failed"
  hint "Check your DATABASE_URL and ensure pgvector extension is enabled"
  hint "SQL: CREATE EXTENSION IF NOT EXISTS vector;"
  echo ""
  echo "You can retry manually: cd packages/db && npx drizzle-kit push"
  exit 1
}
check "Database tables created"
cd "$BODHI_DIR"
echo ""

# ─── Step 12: Start ───
echo -e "${BOLD}Step 10: Starting BODHI...${NC}"
echo ""
bash scripts/start.sh

echo ""
echo -e "${AMBER}${BOLD}  ╔══════════════════════════════════════════╗${NC}"
echo -e "${AMBER}${BOLD}  ║          BODHI is ready!                 ║${NC}"
echo -e "${AMBER}${BOLD}  ╠══════════════════════════════════════════╣${NC}"
echo -e "${AMBER}${BOLD}  ║  Dashboard: http://localhost:4000        ║${NC}"
echo -e "${AMBER}${BOLD}  ║  Telegram:  Message your bot to start!   ║${NC}"
echo -e "${AMBER}${BOLD}  ╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "${DIM}To stop:  bash scripts/stop.sh${NC}"
echo -e "${DIM}To start: bash scripts/start.sh${NC}"
echo ""
